#schema.yml
version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: products
        identifier: raw_gz_product
        description: all products
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: purchse_price
            description: price of the product
            tests:
              - not_null

      - name: sales
        identifier: raw_gz_sales
        description: sales date for gw company
        columns:
          - name: date_date
            description: date of the order
            tests:
              - not_null
          - name: orders_id
            description: primary key
            tests:
              - not_null
          - name: pdt_id
            description: products id
            tests:
              - not_null
          - name: revenue
            tests:
              - not_null
          - name: quantity
            tests:
              - not_null

      - name: ships
        identifier: raw_gz_ship
        description: shipment info about orders
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
          - name: shipping_fee
            tests:
              - not_null
          - name: shipping_fee_1
            tests:
              - not_null
          - name: logCost
            tests:
              - not_null
          - name: ship_cost
            tests:
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: adwords raw data
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null
          - name: camPGN_name
            tests:
              - not_null
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null
              
      - name: bing
        identifier: raw_gz_bing
        description: bing raw data
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null
          - name: camPGN_name
            tests:
              - not_null
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null

      - name: criteo
        identifier: raw_gz_criteo
        description: criteo raw data
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null
          - name: camPGN_name
            tests:
              - not_null
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null

      - name: facebook
        identifier: raw_gz_facebook
        description: facebook raw data
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null
          - name: camPGN_name
            tests:
              - not_null
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null

models:

  - name: int_campaigns
    description: whole data from all campaigns
    columns:
      - name: date_date
        tests:
        - not_null
      - name: paid_source
        tests:
        - not_null
      - name: campaign_key
        tests:
        - not_null
      - name: campaign_name
        tests:
        - not_null
      - name: ads_cost
        tests:
        - not_null
      - name: impression
        tests:
        - not_null
      - name: click
        tests:
        - not_null  